### ISSUE TITLE
No intermediate trees for POJO construction

### ISSUE THREAD

**Issue by ghost** [mmimica/async-jackson#1]
@mmimica I'm a big fan of your actson library, you've done a great thing and here's a big thank you. Are you aware of any library that builds POJO without building the full JsonNode tree first though? Or do you perhaps plan on implementing that in this repository?

**Comment by mmimica** [comment]
First of all, I'm not the author of actson library. I merely used it here because of non-blocking parser.

Second, you made me look at thins code again, and I realized that Jackons 2.9 actually has a non-blocking parser. I have just pushed my changes to not use actson at all.

And, yes, I would also love to have a streaming non-blocking json -> POJO mapper, but it's not going to happen here. Jackson doesn't support it, and I don't have intention to write one.

**Comment by ghost** [comment]
Ah, my mistake. Thanks for the info.
